/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://libraries.minecraft.net/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    compileOnly(libs.org.spigotmc.spigot.api)
    compileOnly(libs.com.mojang.authlib)
}

group = "Achoowy"
version = "0.0.1-SNAPSHOT"
description = "Cameras"
java.sourceCompatibility = JavaVersion.VERSION_1_9

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
