settings:
  camera:
    shadows: true
    permissions: true
    pdc:
      # PDC tag to mark items as cameras (can be any string)
      tag: "camera"
    transparentWater: true
    #disabling async may cause minor lag spikes. enabling async will cause slower rendering, but won't affect server performance
    renderAsync: true
  messages:
    notready: '<red>Cameras is still loading, please wait.'
    invfull: '<red>You can not take a picture with a full inventory.'
    delay: '<red>Please wait before taking another picture.'
    nopaper: '<red>You must have paper in order to take a picture.'
    success: '<green>Picture taken successfully!'
  delay:
    amount: 1000
    enabled: true
